import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Cantata_One } from "next/font/google";
import "./globals.css";
import React from "react";
import Navigation from "../components/Navigation/Navigation";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"], variable: '--font-primary' });
const cantataOne = Cantata_One({
  subsets: ["latin"],
  weight: "400",
  variable: '--font-headline'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="de" className={`${plusJakartaSans.variable} ${cantataOne.variable}`}>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
